CREATE TABLE `user`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `loginId` VARCHAR(16) NOT NULL,
    `password` VARCHAR(128) NOT NULL,
    `nickname` VARCHAR(8) NOT NULL,
    `profileImagePath` TEXT,
    `phoneNumber` VARCHAR(16) NOT NULL,
    `introduce` TEXT,
    `region` VARCHAR(32) NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `post`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` INT NOT NULL,
    `title` VARCHAR(32) NOT NULL,
    `content` TEXT NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `comment`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` INT NOT NULL,
    `postId` INT NOT NULL,
    `content` TEXT NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `trade`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` INT NOT NULL,
    `title` VARCHAR(32) NOT NULL,
    `content` TEXT NOT NULL,
    `price` INT NOT NULL,
    `type` VARCHAR(16) NOT NULL,
    `tradeLocation` VARCHAR(128),
    `state` VARCHAR(4) NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `image`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `postId` INT,
    `url` VARCHAR(128) NOT NULL,
    `type` VARCHAR(8) NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `chat`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `hostId` INT NOT NULL,
    `guestId` INT NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `message`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `chatId` INT NOT NULL,
    `userId` INT NOT NULL,
    `content` VARCHAR(256) NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;